name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  esbuild:
    name: esbuild CI
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.0
        id: go

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make git work
        run: |
          git config --global user.email 'email@example.com'
          git config --global user.name 'example name'

      - name: npm ci
        run: npm ci

      - name: npm test
        run: npm test
